name: Bug
description: Report a bug
labels:
  - bug
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Give some context as to what the bug is.
      placeholder: Some information about the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        List the steps required to reproduce the bug.
      placeholder: |
        1. ...
        2. ...
        3. ...
        4. ...
    validations:
      required: true
  - type: textarea
    id: expected-results
    attributes:
      label: Expected results
      description: Detail what was expected to happen
    validations:
      required: true
  - type: textarea
    id: actual-results
    attributes:
      label: Actual results
      description: Detail the actual results
    validations:
      required: true