name: Security checks
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
permissions:
  actions: read
  contents: read
  security-events: write
jobs:
  review:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - python
    steps:
      - uses: actions/checkout@v3
      - name: Review dependencies
        uses: actions/dependency-review-action@v2
        if: ${{ github.event_name.pull_request }}
      - name: Review dependencies
        uses: actions/dependency-review-action@v2
        if: ${{ github.event_name.push }}
        with:
          base_ref: ${{ github.ref }}
          head_ref: ${{ github.ref }}
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{ matrix.language }}"