name: Run test tooling
on:
  workflow_run:
    workflows:
      - Security checks
    types:
      - completed
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == "success" }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: python -m pip install -e .[dev]
    - name: Run tox to execute all test tooling
      run: tox